### ISSUE TITLE
Support GHC-8.2

### ISSUE THREAD

**Issue by ethercrow** [yi-editor/dynamic-state#2]
`Typeable` stuff changed significantly in base (`Data.Typeable.Internal` is gone from base).

**Comment by noughtmare** [comment]
You might already know this and I don't know a lot about it, but isn't the new [`Type.Reflection`](https://hackage.haskell.org/package/base-4.10.0.0/docs/Type-Reflection.html) module the replacement?

**Comment by ethercrow** [comment]
Yeah, I made a branch https://github.com/yi-editor/dynamic-state/tree/ghc-8.2 that compiles with 8.2, but vim tests in yi fail with it. I haven't gotten to the bottom of this yet.

**Comment by DanBurton** [comment]
Here's the build failure observed on the Stackage build server:

```
[1 of 3] Compiling Data.ConcreteTypeRep ( src/Data/ConcreteTypeRep.hs, dist/build/Data/ConcreteTypeRep.o )

src/Data/ConcreteTypeRep.hs:57:1: error:
    Could not find module ‘Data.Typeable.Internal’
    it is a hidden module in the package ‘base-4.10.0.0’
    Use -v to see a list of the files searched for.
   |
57 | import Data.Typeable.Internal
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by noughtmare** [comment]
@DanBurton Stackage is not compiling the ghc-8.2 branch, so that error is to be expected. But thanks anyway.

**Comment by ethercrow** [comment]
I just released 0.3 that should fix this.
